backend/config/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api/', include('users.urls')),
    path('api/', include('groups.urls')),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.registration.views import StudentCSVUploadView

admin.site.site_header = 'Thesis Review System'
admin.site.site_title = 'Thesis Review System'

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'admin/upload-student-csv/',
        StudentCSVUploadView.as_view(),
        name='upload-student-csv',
    ),
    path(
        '',
        include('website.registration.urls'), name='registration'),
    path(
        '',
        include('website.thesis.urls'), name='thesis'),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

website/registration/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    UserCreateView,
    AboutView,
    LoginRedirectView,
    UserUpdateView,
    UserDeleteView,
    TeachersListView,
    TeacherDetailView,
    StudentDetailView,
    change_password,
    ReportPDFView,
)

app_name = 'registration'

urlpatterns = [
    path(
        '',
        LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    path(
        'logout/',
        LogoutView.as_view(next_page='/'),
        name='logout'),
    path(
        'register/',
        UserCreateView.as_view(),
        name='register'),
    path(
        'about/',
        AboutView.as_view(),
        name='about'),
    path(
        'redirect/',
        LoginRedirectView.as_view(),
        name='login_redirect'),
    path(
        'account/',
        UserUpdateView.as_view(),
        name='user_update'),
    path(
        'account/change-password/',
        change_password,
        name='change_password'),
    path(
        'delete/',
        UserDeleteView.as_view(),
        name='user_delete'),
    path(
        'teachers/',
        TeachersListView.as_view(),
        name='teacher_list'),
    path(
        'teachers/department/<str:department_name>/',
        TeachersListView.as_view(),
        name='teacher_list_department'),
    path(
        'teachers/<username>/',
        TeacherDetailView.as_view(),
        name='teacher_detail'),
    path(
        'students/<username>/',
        StudentDetailView.as_view(),
        name='student_detail'),
    path(
        'reports/<str:department>/<int:batch_id>/',
        ReportPDFView.as_view(),
        name='report_pdf'),
]

website/thesis/urls.py
from django.urls import path

from . import views


app_name = 'thesis'

urlpatterns = [
    path(
        'group/documents/',
        views.DocumentListView.as_view(),
        name='document_list'),
    path(
        'group/create_join/',
        views.GroupCreateJoinView.as_view(),
        name='group_create_join'),
    path(
        'group/create/',
        views.GroupCreateView.as_view(),
        name='group_create'),
    # path(
    #     'group/create/field/<field_id>/teachers/',
    #     views.get_teachers_list_by_field_json,
    #     name='get_teachers'
    # ),
    path(
        'group/join/',
        views.GroupJoinView.as_view(),
        name='group_join'),
    path(
        'group/upload/',
        views.DocumentUploadView.as_view(),
        name='document_upload'),
    path(
        'group/logbooks/create/',
        views.LogbookCreateView.as_view(),
        name='logbook_upload',),
    path(
        'group/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail',),
    path(
        'group/invite/',
        views.GroupInviteView.as_view(),
        name='group_invite'),
    path(
        'group/update/',
        views.GroupUpdateView.as_view(),
        name='group_update'),
    path(
        'group/list/',
        views.GroupListView.as_view(),
        name='group_list'),
    path(
        'group/list/<int:batch_number>/',
        views.GroupListView.as_view(),
        name='group_list_batch'),
    path(
        'internal-group/list/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'internal-group/list/<int:batch_number>/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'external-group/list/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'external-group/list/<int:batch_number>/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'group/notifications/',
        views.NotificationListView.as_view(),
        name='user_notifications'),
    path(
        'group/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create'
    ),
    path(
        'group/<group_code>/',
        views.DocumentListView.as_view(),
        name='group_detail'),
    path(
        'group/<group_code>/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail'),
    path(
        'group/<group_code>/toggle-logbook/<logbook_id>/',
        views.LogbookApprovedToggleView.as_view(),
        name='toggle-logbook-approval'),
    path(
        'group/<group_code>/toggle-document/<document_id>/',
        views.DocumentAcceptedToggleView.as_view(),
        name='group_document_toggle_view'),
    path(
        'group/<group_code>/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create_teacher'
    ),
    path(
        'group/<group_code>/approve/',
        views.StudentGroupApproveView.as_view(),
        name='group_approve'
    ),
    path(
        'group/<group_code>/grading/',
        views.grade_students,
        name='grading_students'
    ),
    path(
        'group/<group_code>/update_progress/',
        views.StudentGroupProgressUpdateView.as_view(),
        name='progress_update'
    ),
]

templates/base/base.html
{% load static %}

<!doctype html>
<html>
{% block html %}
    <head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" href="{% static 'assets/favicon.png' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'assets/favicon.png' %}" type="image/x-icon">
        {% block css %}
        <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fa-svg-with-js.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
            {% block extra_css %}
            {% endblock extra_css %}
        {% endblock css %}

        <title>{% block title %}Thesis Review System{% endblock title %}</title>
    {% endblock head %}
    </head>

    <body>
    {% block body %}
        {% block navbar %}
            {% include 'include/navbar.html' %}
        {% endblock navbar %}

        {% block content %}
        {% endblock content %}
        <footer class="footer">
            <div class="container is-fluid">
                <div class="content has-text-centered">
                <p class="is-size-7">Created by: Md. Shakib Hossain and Towhidul Alam.</p>
                </div>
            </div>
        </footer>

        {% block js %}
        <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
        <script src="{% static 'js/navbar.js' %}"></script>
        <script src="{% static 'js/vue.dev.js' %}"></script>
            {% block extra_js %}
            {% endblock extra_js %}
        {% endblock js %}
    {% endblock body %}
    </body>
{% endblock html %}
</html>

templates/base/base_hero.html
{% extends 'base/base.html' %}
{% load static %}
{% load my_tags %}

{% block body %}
<section class="hero is-transparent is-fullheight">
  <div class="hero-bg"></div>
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    {% block navbar %}
      {% include 'include/navbar.html' %}
    {% endblock navbar %}
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      {% if messages %}
        <div class="columns">
          <div class="column is-4 is-offset-4">
            {% include "include/messages.html" %}
          </div>
        </div>
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
  <div class="hero-foot has-text-centered">
    <p class="is-size-7">&copy; IIUC 2020</p>
  </div>
</section>

    {% block js %}
    {{ block.super }}
    {% endblock js %}
{% endblock body %}

templates/base/thesis_dashboard_base.html
{% extends 'base/base.html' %}
{% load static %}
{% load my_tags %}

{% block extra_css %}
<style>
    nav.navbar {
        border-bottom: 2px #276cda solid;
    }
    .group-details-text-container {
      display: inline-block;
      margin-bottom: 3px;
    }
</style>
{% endblock extra_css %}


{% block content %}
{% url 'thesis:document_list' as document_list %}
{% url 'registration:teacher_list' as teacher_list %}
{% url 'thesis:document_upload' as document_upload %}
{% url 'thesis:group_list' as group_list %}
{% url 'thesis:internal_group_list' as internal_group_list %}
{% url 'thesis:external_group_list' as external_group_list %}
{% url 'thesis:group_invite' as group_invite %}
{% url 'thesis:group_update' as group_update %}
{% url 'thesis:group_create' as group_create %}
{% url 'thesis:group_join' as group_join %}
{% url 'thesis:user_notifications' as user_notifications %}
{% url 'registration:user_update' as user_update %}
{% url 'registration:change_password' as change_password %}
{% url 'registration:logout' as logout %}
{% url 'registration:user_delete' as user_delete %}

<div class="container is-fluid" id="main-container">
    <div class="columns">
        <div class="column is-2" style="min-width: 210px;">
            <aside class="menu has-text-weight-bold">
                <p class="menu-label">General</p>
                <ul class="menu-list">
                  <li>
                    <a href="{{ teacher_list }}"
                      {% if request.path == teacher_list %}class="is-active"{% endif %}>
                      <i class="fas fa-chalkboard-teacher"></i>&nbsp; Teachers
                    </a>
                  </li>
                </ul>
                <p class="menu-label">Group</p>
                <ul class="menu-list">
                    {% if user.is_teacher %}
                      {% if user.is_external %}
                      <li><a href="{{ external_group_list }}"
                      class="{% if request.path|startswith:external_group_list %}is-active{% endif %}">
                          <i class="fas fa-align-justify"></i>&nbsp; Groups</a></li>
                      {% else %}
                      <li><a href="{{ group_list }}"
                      class="{% if request.path|startswith:group_list %}is-active{% endif %}">
                          <i class="fas fa-align-justify"></i>&nbsp; Groups</a></li>
                      <li><a href="{{ internal_group_list }}"
                      class="{% if request.path|startswith:internal_group_list %}is-active{% endif %}">
                          <i class="fas fa-align-justify"></i>&nbsp; Groups(As Reviewer)</a></li>
                      {% endif %}
                      {% if user.is_superuser %}
                        <li><a href="/admin">
                            <i class="fas fa-align-justify"></i>&nbsp; Admin Panel</a></li>
                      {% endif %}
                    {% elif user.studentgroup %}
                    <li><a href="{{ document_list }}"
                    class="{% if request.path == document_list %}is-active{% endif %}">
                        <i class="fas fa-align-justify"></i>&nbsp; Documents</a></li>
                    <li><a href="{{ document_upload }}"
                    class="{% if request.path == document_upload %}is-active{% endif %}">
                        <i class="fas fa-upload"></i>&nbsp; Upload</a></li>
                    {% comment %} <li><a href="{{ group_invite }}"
                    class="{% if request.path == group_invite %}is-active{% endif %}">
                        <i class="fas fa-share"></i>&nbsp; Invite</a></li> {% endcomment %}
                    <li><a href="{{ group_update }}"
                    class="{% if request.path == group_update %}is-active{% endif %}">
                        <i class="fas fa-wrench"></i>&nbsp; Group Settings</a></li>
                    {% else %}
                    <li><a href="{{ group_create }}"
                    class="{% if request.path == group_create %}is-active{% endif %}">
                        <i class="fas fa-plus"></i>&nbsp; Create Group</a></li>
                    <li><a href="{{ group_join }}"
                    class="{% if request.path == group_join %}is-active{% endif %}">
                        <i class="fas fa-sign-in-alt"></i>&nbsp; Join Group</a></li>
                    {% endif %}
                </ul>
                <p class="menu-label">Account</p>
                <ul class="menu-list">
                    <li><a href="{{ user_notifications }}"
                        class="{% if request.path == user_notifications %}is-active{% endif %}">
                        <i class="fas fa-bell" ></i>&nbsp; Notifications {% if unread_notifications_count %}<b>({{unread_notifications_count}})</b>{% endif %}</a></li>
                    <li><a href="{{ user_update }}"
                        class="{% if request.path == user_update %}is-active{% endif %}">
                        <i class="fas fa-cog"></i>&nbsp; Profile Settings</a></li>
                    <li><a href="{{ change_password }}"
                        class="{% if request.path == change_password %}is-active{% endif %}">
                        <i class="fas fa-key"></i>&nbsp; Change Password</a></li>
                    <li><a href="{{ logout }}"
                        class="{% if request.path == logout %}is-active{% endif %}">
                        <i class="fas fa-sign-out-alt"></i>&nbsp; Logout</a></li>
                    {% comment %} <li><a href="{{ user_delete }}"
                        class="{% if request.path == user_delete %}is-active{% endif %}">
                        <i class="fas fa-trash"></i>&nbsp; Account Removal</a></li> {% endcomment %}
                </ul>
            </aside>
        </div>
        <div class="column">
            <div class="columns is-multiline">

                {% include "include/messages.html" %}

                <div class="column">
                    {% block page_title %}
                        {% if studentgroup %}
                        <h3 class="title">{{ studentgroup.title }}</h3>
                        <h4 class="subtitle is-size-6">
                          <span class="group-details-text-container">
                            <b>Status: </b>
                            <span class="tag {% if not studentgroup.approved or studentgroup.status == 'Pending' %}is-danger{% elif studentgroup.status == 'Defense Done' %}is-success{% else %}is-link{% endif %}">
                                  {% if not studentgroup.approved %}
                                    Pending Admin Approval
                                  {% else %}
                                    {{ studentgroup.status }}
                                  {% endif %}
                              </span>
                          </span>
                          <br/>
                          {% if user.is_teacher %}
                            <span class="group-details-text-container">
                              <b>Grading Status:</b>
                              {% if graded %}
                                <span class="tag is-success">
                                  Graded
                                </span>
                              {% else %}
                                {% if studentgroup.status == 'Defense Done' %}
                                <a href="{% url 'thesis:grading_students' studentgroup.md5hash %}" class="tag is-danger">
                                  Ready for grading
                                </a>
                                {% else %}
                                <span class="tag is-danger">
                                  Defense Report Must be Accepted
                                </span>
                                {% endif %}
                              {% endif %}
                            </span>
                            <br>
                          {% endif %}
                          <span class="group-details-text-container">
                            <b>Research Field: </b>
                              {% if studentgroup.field %}
                                <span class="tag is-link">{{ studentgroup.field.name }}</span>
                              {% else %}
                                <span class="tag is-danger">Not assigned yet!</span>
                              {% endif %}
                          </span>
                          <br>
                          <span class="group-details-text-container">
                            <b>Supervisor: </b>
                              {% if studentgroup.teacher %}
                                <a href="{% url 'registration:teacher_detail' studentgroup.teacher.username %}" class="tag is-link">
                                {{ studentgroup.teacher }}
                                </a>
                              {% else %}
                                <span class="tag is-danger">Not assigned yet!</span>
                              {% endif %}
                          </span>
                          <br>
                          <span class="group-details-text-container">
                          <b>Members: </b>
                            {% for student in studentgroup.students.all %}
                              <a
                                href="{% if user == student %}/account/{% else %}{% url 'registration:student_detail' student.username %}{% endif %}"
                                class="tag is-link">{{ student }}</a>
                            {% endfor %}
                          </span>
                        </h4>
                        {% else %}
                        <h3 class="title">Groups</h3>
                        {% endif %}
                    {% endblock page_title %}
                </div>
            </div>
            <div class="columns is-desktop mb-4">
                {% block dashboard_content %}
                {% endblock dashboard_content %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}