backend/config/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api/', include('users.urls')),
    path('api/', include('groups.urls')),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.registration.views import StudentCSVUploadView

admin.site.site_header = 'Thesis Review System'
admin.site.site_title = 'Thesis Review System'

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'admin/upload-student-csv/',
        StudentCSVUploadView.as_view(),
        name='upload-student-csv',
    ),
    path(
        '',
        include('website.registration.urls'), name='registration'),
    path(
        '',
        include('website.thesis.urls'), name='thesis'),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

website/registration/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    UserCreateView,
    AboutView,
    LoginRedirectView,
    UserUpdateView,
    UserDeleteView,
    TeachersListView,
    TeacherDetailView,
    StudentDetailView,
    change_password,
    ReportPDFView,
)

app_name = 'registration'

urlpatterns = [
    path(
        '',
        LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    path(
        'logout/',
        LogoutView.as_view(next_page='/'),
        name='logout'),
    path(
        'register/',
        UserCreateView.as_view(),
        name='register'),
    path(
        'about/',
        AboutView.as_view(),
        name='about'),
    path(
        'redirect/',
        LoginRedirectView.as_view(),
        name='login_redirect'),
    path(
        'account/',
        UserUpdateView.as_view(),
        name='user_update'),
    path(
        'account/change-password/',
        change_password,
        name='change_password'),
    path(
        'delete/',
        UserDeleteView.as_view(),
        name='user_delete'),
    path(
        'teachers/',
        TeachersListView.as_view(),
        name='teacher_list'),
    path(
        'teachers/department/<str:department_name>/',
        TeachersListView.as_view(),
        name='teacher_list_department'),
    path(
        'teachers/<username>/',
        TeacherDetailView.as_view(),
        name='teacher_detail'),
    path(
        'students/<username>/',
        StudentDetailView.as_view(),
        name='student_detail'),
    path(
        'reports/<str:department>/<int:batch_id>/',
        ReportPDFView.as_view(),
        name='report_pdf'),
]

website/thesis/urls.py
from django.urls import path

from . import views


app_name = 'thesis'

urlpatterns = [
    path(
        'group/documents/',
        views.DocumentListView.as_view(),
        name='document_list'),
    path(
        'group/create_join/',
        views.GroupCreateJoinView.as_view(),
        name='group_create_join'),
    path(
        'group/create/',
        views.GroupCreateView.as_view(),
        name='group_create'),
    # path(
    #     'group/create/field/<field_id>/teachers/',
    #     views.get_teachers_list_by_field_json,
    #     name='get_teachers'
    # ),
    path(
        'group/join/',
        views.GroupJoinView.as_view(),
        name='group_join'),
    path(
        'group/upload/',
        views.DocumentUploadView.as_view(),
        name='document_upload'),
    path(
        'group/logbooks/create/',
        views.LogbookCreateView.as_view(),
        name='logbook_upload',),
    path(
        'group/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail',),
    path(
        'group/invite/',
        views.GroupInviteView.as_view(),
        name='group_invite'),
    path(
        'group/update/',
        views.GroupUpdateView.as_view(),
        name='group_update'),
    path(
        'group/list/',
        views.GroupListView.as_view(),
        name='group_list'),
    path(
        'group/list/<int:batch_number>/',
        views.GroupListView.as_view(),
        name='group_list_batch'),
    path(
        'internal-group/list/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'internal-group/list/<int:batch_number>/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'external-group/list/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'external-group/list/<int:batch_number>/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'group/notifications/',
        views.NotificationListView.as_view(),
        name='user_notifications'),
    path(
        'group/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create'
    ),
    path(
        'group/<group_code>/',
        views.DocumentListView.as_view(),
        name='group_detail'),
    path(
        'group/<group_code>/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail'),
    path(
        'group/<group_code>/toggle-logbook/<logbook_id>/',
        views.LogbookApprovedToggleView.as_view(),
        name='toggle-logbook-approval'),
    path(
        'group/<group_code>/toggle-document/<document_id>/',
        views.DocumentAcceptedToggleView.as_view(),
        name='group_document_toggle_view'),
    path(
        'group/<group_code>/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create_teacher'
    ),
    path(
        'group/<group_code>/approve/',
        views.StudentGroupApproveView.as_view(),
        name='group_approve'
    ),
    path(
        'group/<group_code>/grading/',
        views.grade_students,
        name='grading_students'
    ),
    path(
        'group/<group_code>/update_progress/',
        views.StudentGroupProgressUpdateView.as_view(),
        name='progress_update'
    ),
]

templates/include/comment_item.html
<div class="comment px-3">
    <div class="tags has-addons" style="display:inline-block;margin-bottom:0;">
        {% if comment.user.is_teacher %}
            <span class="tag is-danger">
                {% if comment.user == studentgroup.teacher %}
                    Supervisor
                {% elif comment.user == studentgroup.internal %}
                    Internal
                {% elif comment.user == studentgroup.external %}
                    External
                {% endif %}
            </span>
        {% else %}
            <span class="tag is-link">Student</span>
        {% endif %}
        <span class="tag">{{ comment.user }}</span>
    </div>
    <p class="is-size-7" style="margin-bottom:0em;display:inline-block;">
        {{ comment.created_at|date:"d M Y" }}
        at
        {{ comment.created_at|date:"H:i" }}
    </p>
    <p class="is-size-6">{{ comment.content|linebreaksbr }}</p>
</div>

templates/include/document_list_tab.html
{% load static %}

<div id="{{ container_id }}" class="content-tab" style="{{ style }}">
    {% if documents %}
        {% for d in documents %}
        <div class="columns is-mobile panel-block">
            <div class="column is-7 has-text-small">
                {{ d.filename }} {% if d.is_accepted %}<span title="Accepted" class="fas fa-check-circle has-text-success"></span>{% endif %}
                <br>
                <p class="is-size-7">
                    <span class="icon"><i class="fas fa-upload"></i></span>
                    <time datetime="{{ d.upload_time }}">
                        {{ d.upload_time|date:"d M Y" }} - {{ d.upload_time|date:"H:i" }}
                    </time>
                </p>
            </div>
            <div class="column has-text-right">
                <a
                    href="{% get_media_prefix %}/sg_{{ studentgroup.md5hash }}/{{ d.filename }}"
                    data-sg-code="{{ studentgroup.md5hash }}"
                    data-file-name="{{ d.filename }}"
                    title="View"
                    class="button is-small is-link view-button">
                    <span class="icon"><i class="fas fa-eye"></i></span>
                </a>
                <a
                    href="{% get_media_prefix %}/sg_{{ studentgroup.md5hash }}/{{ d.filename }}"
                    title="Download"
                    target="_blank"
                    class="button is-small is-info">
                    <span class="icon"><i class="fas fa-download"></i></span>
                </a>
                {% if user == studentgroup.teacher %}
                    {% if d.is_accepted %}
                        <button
                            title="Disapprove"
                            data-btn-type="disapprove"
                            data-doc-id="{{ d.id }}"
                            class="button is-small is-danger appr-btn">
                            <span class="icon"><i class="fas fa-times"></i></span>
                        </button>
                    {% else %}
                        <button
                            title="Approve"
                            data-btn-type="approve"
                            data-doc-id="{{ d.id }}"
                            class="button is-small is-success appr-btn">
                            <span class="icon"><i class="fas fa-check"></i></span>
                        </button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% endfor %}
    {% else %}
        {% include "include/no_documents.html" %}
    {% endif %}
</div>

templates/include/logbook_list.html
<div class="content-tab" style="{{ style }}">
    {% if logbooks %}
        {% for d in logbooks %}
        <div class="columns is-mobile panel-block">
            <div class="column is-7 has-text-small">
                Logbook ID: {{ d.id }} {% if d.approved %}<span title="Accepted" class="fas fa-check-circle has-text-success"></span>{% endif %} <br>
                <p class="is-size-7">
                    <span class="icon"><i class="fas fa-upload"></i></span>
                    <time datetime="{{ d.time }}">
                        {{ d.time|date:"d M Y" }} - {{ d.time|date:"H:i" }}
                    </time>
                </p>
            </div>
            <div class="column has-text-right">
                <a
                    {% if not user.is_teacher %}
                        href="{% url 'thesis:logbook_detail' pk=d.id  %}"
                    {% else %}
                        href="{% url 'thesis:logbook_detail' group_code=studentgroup.md5hash pk=d.id  %}"
                    {% endif %}
                    data-sg-code="{{ studentgroup.md5hash }}"
                    data-file-name="{{ d.filename }}"
                    title="View"
                    class="button is-small is-link">
                    <span class="icon"><i class="fas fa-eye"></i></span>
                </a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        {% include "include/no_logbooks.html" %}
    {% endif %}
</div>

templates/include/messages.html
{% if messages %}
<div class="column is-12">
    {% for message in messages %}
    <div class="message {{ message.tags }}">
        <div class="message-body">
            {{ message }}
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/include/navbar.html
{% load static %}

<nav class="navbar is-light has-background-light">
    <div class="container is-fluid">
        <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'registration:login' %}">
            <img src="{% static 'assets/iiuc-small-logo.png' %}" alt="IIUC Logo" style="height: 35px;" class="mr-2">
            <h1 class="has-text-weight-bold">
                Thesis Review System
            </h1>
        </a>
        <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
        </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
                {% url 'registration:login' as login %}
                {% url 'registration:register' as register %}
                {% url 'registration:about' as about %}
                {% url 'registration:user_update' as user_update %}
                {% url 'registration:teacher_list' as teacher_list %}
                {% url 'thesis:group_list' as group_list %}
                {% if user.is_authenticated %}
                    <span class="navbar-item">
                        Logged in as: ({{ user.username }})
                    </span>
                    <a href="{{ teacher_list }}"
                        class="navbar-item {% if request.path == teacher_list %}is-active{% endif %}">
                        Teachers
                    </a>
                    <a href="{{ user_update }}"
                        class="navbar-item {% if request.path == user_update %}is-active{% endif %}">
                        Profile
                    </a>
                    {% if user.is_teacher %}
                    <a href="{{ group_list }}"
                        class="navbar-item {% if request.path == group_list %}is-active{% endif %}">
                        Groups
                    </a>
                    {% endif %}
                    <!-- <div class="navbar-item  has-dropdown is-hoverable">
                        <a class="navbar-link" href="#">
                            Group
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{% url 'thesis:group_create' %}">
                                Create
                            </a>
                            <a class="navbar-item" href="{% url 'thesis:group_join' %}">
                                Join
                            </a>
                        </div>
                    </div> -->
                    <a href="{% url 'registration:logout' %}"
                        class="navbar-item">
                        Logout
                    </a>
                {% else %}
                    <a class="navbar-item {% if request.path == login %}is-active{% endif %}"
                        href="{% url 'registration:login' %}">
                    Login
                    </a>
                    <a class="navbar-item {% if request.path == register %}is-active{% endif %}"
                        href="{% url 'registration:register' %}">
                    Register
                    </a>
                    <!-- <a class="navbar-item {% if request.path == about %}is-active{% endif %}"
                        href="{% url 'registration:about' %}">
                    About
                    </a> -->
                {% endif %}
            </div>
        </div>
    </div>
</nav>

templates/include/no_documents.html
<div class="content has-text-centered">
    <div class="hero is-medium">
        <div class="hero-body">
            <p>
                No Documents Submitted Yet!
            </p>
            {% if not user.is_teacher %}
            <p>
                <a href="{% url 'thesis:document_upload' %}" class="button is-link">
                    <i class="fas fa-upload"></i>&nbsp; Submit Now!
                </a>
            </p>
            {% endif %}
        </div>
    </div>
</div>

templates/include/no_logbooks.html
<div class="content has-text-centered">
    <div class="hero is-medium">
        <div class="hero-body">
            <p>
                No Logbooks Submitted Yet!
            </p>
            {% if not user.is_teacher %}
            <p>
                <a href="{% url 'thesis:logbook_upload' %}" class="button is-link">
                    <i class="fas fa-upload"></i>&nbsp; Submit Now!
                </a>
            </p>
            {% endif %}
        </div>
    </div>
</div>