backend/config/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api/', include('users.urls')),
    path('api/', include('groups.urls')),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from website.registration.views import StudentCSVUploadView

admin.site.site_header = 'Thesis Review System'
admin.site.site_title = 'Thesis Review System'

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'admin/upload-student-csv/',
        StudentCSVUploadView.as_view(),
        name='upload-student-csv',
    ),
    path(
        '',
        include('website.registration.urls'), name='registration'),
    path(
        '',
        include('website.thesis.urls'), name='thesis'),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
) + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

website/registration/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    UserCreateView,
    AboutView,
    LoginRedirectView,
    UserUpdateView,
    UserDeleteView,
    TeachersListView,
    TeacherDetailView,
    StudentDetailView,
    change_password,
    ReportPDFView,
)

app_name = 'registration'

urlpatterns = [
    path(
        '',
        LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    path(
        'logout/',
        LogoutView.as_view(next_page='/'),
        name='logout'),
    path(
        'register/',
        UserCreateView.as_view(),
        name='register'),
    path(
        'about/',
        AboutView.as_view(),
        name='about'),
    path(
        'redirect/',
        LoginRedirectView.as_view(),
        name='login_redirect'),
    path(
        'account/',
        UserUpdateView.as_view(),
        name='user_update'),
    path(
        'account/change-password/',
        change_password,
        name='change_password'),
    path(
        'delete/',
        UserDeleteView.as_view(),
        name='user_delete'),
    path(
        'teachers/',
        TeachersListView.as_view(),
        name='teacher_list'),
    path(
        'teachers/department/<str:department_name>/',
        TeachersListView.as_view(),
        name='teacher_list_department'),
    path(
        'teachers/<username>/',
        TeacherDetailView.as_view(),
        name='teacher_detail'),
    path(
        'students/<username>/',
        StudentDetailView.as_view(),
        name='student_detail'),
    path(
        'reports/<str:department>/<int:batch_id>/',
        ReportPDFView.as_view(),
        name='report_pdf'),
]

website/thesis/urls.py
from django.urls import path

from . import views


app_name = 'thesis'

urlpatterns = [
    path(
        'group/documents/',
        views.DocumentListView.as_view(),
        name='document_list'),
    path(
        'group/create_join/',
        views.GroupCreateJoinView.as_view(),
        name='group_create_join'),
    path(
        'group/create/',
        views.GroupCreateView.as_view(),
        name='group_create'),
    # path(
    #     'group/create/field/<field_id>/teachers/',
    #     views.get_teachers_list_by_field_json,
    #     name='get_teachers'
    # ),
    path(
        'group/join/',
        views.GroupJoinView.as_view(),
        name='group_join'),
    path(
        'group/upload/',
        views.DocumentUploadView.as_view(),
        name='document_upload'),
    path(
        'group/logbooks/create/',
        views.LogbookCreateView.as_view(),
        name='logbook_upload',),
    path(
        'group/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail',),
    path(
        'group/invite/',
        views.GroupInviteView.as_view(),
        name='group_invite'),
    path(
        'group/update/',
        views.GroupUpdateView.as_view(),
        name='group_update'),
    path(
        'group/list/',
        views.GroupListView.as_view(),
        name='group_list'),
    path(
        'group/list/<int:batch_number>/',
        views.GroupListView.as_view(),
        name='group_list_batch'),
    path(
        'internal-group/list/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'internal-group/list/<int:batch_number>/',
        views.InternalGroupListView.as_view(),
        name='internal_group_list'),
    path(
        'external-group/list/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'external-group/list/<int:batch_number>/',
        views.ExternalGroupListView.as_view(),
        name='external_group_list'),
    path(
        'group/notifications/',
        views.NotificationListView.as_view(),
        name='user_notifications'),
    path(
        'group/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create'
    ),
    path(
        'group/<group_code>/',
        views.DocumentListView.as_view(),
        name='group_detail'),
    path(
        'group/<group_code>/logbooks/<int:pk>/',
        views.LogbookDetailView.as_view(),
        name='logbook_detail'),
    path(
        'group/<group_code>/toggle-logbook/<logbook_id>/',
        views.LogbookApprovedToggleView.as_view(),
        name='toggle-logbook-approval'),
    path(
        'group/<group_code>/toggle-document/<document_id>/',
        views.DocumentAcceptedToggleView.as_view(),
        name='group_document_toggle_view'),
    path(
        'group/<group_code>/comment/create/',
        views.CommentCreateView.as_view(),
        name='comment_create_teacher'
    ),
    path(
        'group/<group_code>/approve/',
        views.StudentGroupApproveView.as_view(),
        name='group_approve'
    ),
    path(
        'group/<group_code>/grading/',
        views.grade_students,
        name='grading_students'
    ),
    path(
        'group/<group_code>/update_progress/',
        views.StudentGroupProgressUpdateView.as_view(),
        name='progress_update'
    ),
]

website/thesis/models.py
from venv import create
from django.db import models
from django.conf import settings
from django.core import validators
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save, post_delete

import os
from uuid import uuid4
from datetime import datetime

from ..registration.models import DepartmentType


def generate_upload_location(instance, filename):
    filename = filename + str(datetime.now())
    filename = uuid4().hex[:10] + '.pdf'
    return 'sg_{}/{}'.format(
        instance.studentgroup.md5hash,
        filename)


class Batch(models.Model):
    number = models.PositiveSmallIntegerField(unique=True)
    max_groups_num = models.PositiveSmallIntegerField(default=5)
    min_groups_num = models.PositiveSmallIntegerField(default=0)
    max_students_per_group = models.PositiveSmallIntegerField(default=2, validators=[
        validators.MinValueValidator(1),
    ])
    supervisor_mark_percentage = models.PositiveIntegerField(default=50, validators=[
        validators.MaxValueValidator(100),
        validators.MinValueValidator(0),
    ])
    internal_mark_percentage = models.PositiveIntegerField(default=30, validators=[
        validators.MaxValueValidator(100),
        validators.MinValueValidator(0),
    ])
    external_mark_percentage = models.PositiveIntegerField(default=20, validators=[
        validators.MaxValueValidator(100),
        validators.MinValueValidator(0),
    ])

    def clean(self):
        if sum([self.supervisor_mark_percentage, self.internal_mark_percentage, self.external_mark_percentage]) != 100:
            error_message = 'Sum of these must be 100'
            raise ValidationError({
                "supervisor_mark_percentage": error_message,
                "internal_mark_percentage": error_message,
                "external_mark_percentage": error_message,
            })

    class Meta:
        verbose_name_plural = 'batches'

    def __str__(self):
        return f'Batch {self.number}'


class StudentGroup(models.Model):
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        default=None,
        related_name='studentgroups',
        on_delete=models.SET_DEFAULT,
        limit_choices_to={"is_teacher": True},
        verbose_name='Supervisor',
    )
    internal = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        default=None,
        related_name='internal_studentgroups',
        on_delete=models.SET_DEFAULT,
        limit_choices_to={"is_teacher": True},
        verbose_name='Reviewer',
    )
    external = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        default=None,
        related_name='external_studentgroups',
        on_delete=models.SET_DEFAULT,
        limit_choices_to={"is_teacher": True, "is_external": True},
    )
    first_choice = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='first_choice_studentgroups',
        on_delete=models.SET_NULL,
        limit_choices_to={"is_teacher": True}
    )
    second_choice = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='second_choice_studentgroups',
        on_delete=models.SET_NULL,
        limit_choices_to={"is_teacher": True}
    )
    third_choice = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='third_choice_studentgroups',
        on_delete=models.SET_NULL,
        limit_choices_to={"is_teacher": True}
    )
    title = models.CharField(max_length=256)
    department = models.CharField(
        max_length=3,
        choices=DepartmentType.choices,
    )
    md5hash = models.CharField(max_length=10, null=True)
    progress = models.IntegerField(default=0)
    student_list = models.CharField(
        max_length=64,
        blank=True,
        validators=[
            validators.RegexValidator(
                r'(([A-Z]{1,2}\d{6})+)(,\s*([A-Z]{1,2}\d{6})+)*',
            ),
        ],
    )
    approved = models.BooleanField(default=False)
    batch = models.ForeignKey(
        Batch,
        on_delete=models.SET_NULL,
        null=True,
    )
    field = models.ForeignKey(
        'ResearchField',
        null=True,
        default=None,
        related_name='studentgroups',
        on_delete=models.SET_NULL,
    )

    @property
    def max_cgpa(self):
        student = self.students.all().order_by('-cgpa').first()
        if student:
            return student.cgpa
        return 0

    @property
    def status(self):
        documents_queryset = self.documents.filter(is_accepted=True)
        if not self.approved:
            return 'Pending Admin Approval'
        elif documents_queryset.filter(document_type=Document.DocumentType.DEFENSE.value).exists():
            return 'Defense Done'
        elif documents_queryset.filter(document_type=Document.DocumentType.PRE_DEFENSE.value).exists():
            return 'Pre-Defense Done'
        elif documents_queryset.filter(document_type=Document.DocumentType.PROPOSAL.value).exists():
            return 'Proposal Done'
        else:
            return 'Supervisor Approved'

    def graded(self, user):
        return self.marks.filter(graded_by=user).exists()

    class Meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        if not self.md5hash:
            self.md5hash = uuid4().hex[:8]
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.department}_{self.batch.number}_{self.id}'


class Document(models.Model):
    class DocumentType(models.TextChoices):
        PROPOSAL = "Proposal"
        PRE_DEFENSE = "Pre-Defense Report"
        DEFENSE = "Defense Report"

    studentgroup = models.ForeignKey(
        StudentGroup,
        on_delete=models.CASCADE,
        related_name='documents')
    upload_time = models.DateTimeField(auto_now_add=True)
    document_type = models.CharField(
        max_length=24,
        choices=DocumentType.choices,
    )
    file = models.FileField(upload_to=generate_upload_location)
    is_accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ['-upload_time', ]

    def __str__(self):
        return self.filename

    @property
    def filename(self):
        return os.path.basename(self.file.name)


class Logbook(models.Model):
    class MeetingType(models.TextChoices):
        ON_SITE = "On-Site"
        ONLINE = "Online"

    studentgroup = models.ForeignKey(
        StudentGroup,
        on_delete=models.CASCADE,
        related_name='logbooks',
    )
    time = models.DateTimeField()
    meeting_type = models.CharField(
        max_length=7,
        choices=MeetingType.choices,
    )
    students_present = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        limit_choices_to={"is_student": True},
    )
    suggestions = models.TextField()
    topic_discussed = models.TextField()
    work_done_after_last_meeting = models.TextField()
    approved = models.BooleanField(default=False)

    class Meta:
        default_related_name = 'logbooks'

    def __str__(self) -> str:
        return f'{self.studentgroup} - {self.time}'


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    studentgroup = models.ForeignKey(
        StudentGroup,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.content[:10] + '...'


class ResearchField(models.Model):
    name = models.CharField(max_length=256)
    teachers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='fields',
        limit_choices_to={'is_teacher': True},
        blank=True
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Notification(models.Model):
    content = models.TextField()
    is_viewed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    studentgroup = models.ForeignKey(
        StudentGroup,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        'registration.User',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['-created_at']
        default_related_name = 'notifications'

    def __str__(self):
        return f'Notification {self.content[:20]}'


@receiver(post_save, sender=Document)
def generate_notification_on_document_upload(sender, instance, created, **kwargs):
    studentgroup = instance.studentgroup
    if created:
        content = f'A new Document({instance.document_type}) was uploaded to {studentgroup}'
        if studentgroup.approved:
            if studentgroup.teacher:
                Notification.objects.create(
                    content=content,
                    user=studentgroup.teacher,
                    studentgroup=studentgroup,
                )
            # if studentgroup.internal:
            #     Notification.objects.create(
            #         content=content,
            #         user=studentgroup.internal,
            #         studentgroup=studentgroup,
            #     )
            # if studentgroup.external:
            #     Notification.objects.create(
            #         content=content,
            #         user=studentgroup.external,
            #         studentgroup=studentgroup,
            #     )
    else:
        if instance.is_accepted:
            content = f'Your {instance.filename}({instance.document_type}) document was approved.'
        else:

templates/thesis/document_list.html
{% extends 'base/thesis_dashboard_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} | {{ studentgroup.title }}
{% endblock title %}

{% block extra_css %}
    {{ block.super }}
    <style>
        .content-tab {
            min-height: 290px;
        }
    </style>
{% endblock extra_css %}


{% block dashboard_content %}
    <div class="column is-12-mobile is-5-desktop is-4-widescreen">
        <section class="panel is-link">
            <p class="panel-heading is-flex" style="justify-content:space-between;">
                <span>Documents</span>
                {% if not user.is_teacher %}
                    <a href="{% url 'thesis:document_upload' %}" class="icon has-text-white">
                        <i class="fas fa-upload"></i>
                    </a>
                {% endif %}
            </p>
            <p class="panel-tabs">
                <a class="is-active" onclick="openTab(event,'proposal_documents')">Proposal</a>
                <a onclick="openTab(event,'pre_defense_documents')">Pre-Defense</a>
                <a onclick="openTab(event,'defense_documents')">Defense</a>
            </p>
        
            {% include "include/document_list_tab.html" with studentgroup=studentgroup container_id="proposal_documents" documents=proposal_documents %}

            {% include "include/document_list_tab.html" with studentgroup=studentgroup container_id="pre_defense_documents" documents=pre_defense_documents style="display:none;" %}

            {% include "include/document_list_tab.html" with studentgroup=studentgroup container_id="defense_documents" documents=defense_documents style="display:none;" %}
        </section>

        {% comment %} Logbooks Panel {% endcomment %}
        {% if user.is_student or user == studentgroup.teacher %}
        <section class="panel is-link">
            <p class="panel-heading is-flex" style="justify-content:space-between;">
                <span>Logbooks</span>
                {% if not user.is_teacher %}
                    <a href="{% url 'thesis:logbook_upload' %}" class="icon has-text-white">
                        <i class="fas fa-upload"></i>
                    </a>
                {% endif %}
            </p>
        
            {% include "include/logbook_list.html" with studentgroup=studentgroup logbooks=logbooks %}
        </section>
        {% endif %}
    </div>
    
    <div class="column">

        {% comment %} Document Viewer {% endcomment %}
        <section class="panel is-hidden mt-4" id="document-viewer">
            <p class="panel-heading is-flex" style="justify-content:space-between;">
                <span>Document Viewer</span>
                <a class="icon has-text-dark" id="document-viewer-close">
                    <i class="fas fa-times"></i>
                </a>
            </p>
            <div class="panel-body">
                <div class="content">
                    <iframe id="iframe"
                    src=""
                    frameborder="0" width="100%" height="500"></iframe>
                </div>
            </div>
        </section>

        <section class="panel is-link pb-4">
            <p class="panel-heading">
                Comments
            </p>
            {% if not user.is_teacher or user == studentgroup.teacher or user == studentgroup.internal or user == studentgroup.external %}
                <form class="px-3 pt-3" method="post"
                {% if user.is_teacher %}
                    action="{% url 'thesis:comment_create_teacher' studentgroup.md5hash %}"
                {% else %}
                    action="{% url 'thesis:comment_create' %}"
                {% endif %}
                >
                    <div class="field">
                        <div class="control">
                            <textarea name="content"
                                class="textarea"
                                rows="2"
                                placeholder="Write your comment here!" required=""></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <p class="control">
                            <button type="submit" class="button is-link">Post</button></p>
                    </div>

                    {% csrf_token %}
                </form>
            {% endif %}
            {% if comments %}
                {% for comment in comments %}
                    {% if user.is_student %}
                        {% if comment.user == studentgroup.teacher or comment.user == studentgroup.internal or comment.user.is_student %}
                            {% include "include/comment_item.html" with comment=comment user=user studentgroup=studentgroup %}
                        {% endif %}
                    {% elif user == studentgroup.teacher %}
                        {% if comment.user.is_student or comment.user == user %}
                            {% include "include/comment_item.html" with comment=comment user=user studentgroup=studentgroup %}
                        {% endif %}
                    {% elif user == studentgroup.internal and user == comment.user %}
                        {% include "include/comment_item.html" with comment=comment user=user studentgroup=studentgroup %}
                    {% elif user == studentgroup.external and user == comment.user %}
                        {% include "include/comment_item.html" with comment=comment user=user studentgroup=studentgroup %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <p class="panel-body">
                    
                </p>
            {% endif %}
        </section>
    </div>
{% endblock dashboard_content %}

{% block extra_js %}
  {{ block.super }}
    <script>
        {% comment %} Code for Showing Document Viewer {% endcomment %}
        var baseURL = "{% static 'pdfjs/web/viewer.html' %}?file=/media/sg_{{ studentgroup.md5hash }}/",
            view_buttons = document.getElementsByClassName('view-button'),
            document_viewer = document.getElementById('document-viewer'),
            document_viewer_close = document.getElementById('document-viewer-close'),
            iframe = document.getElementById('iframe');

        for (var i = 0; i < view_buttons.length; ++i) {
            view_button = view_buttons.item(i);
            view_button.onclick = function (e) {
                e.preventDefault();
                var fileName = this.getAttribute('data-file-name');
                const iframeSrc = baseURL + fileName;
                const currentIframeSrc = iframe.getAttribute('src');
                if (currentIframeSrc != iframeSrc)
                    iframe.setAttribute('src', baseURL + fileName);
                document_viewer.classList.remove('is-hidden');
            }
        }

        document_viewer_close.onclick = function(e) {
            e.preventDefault();
            document_viewer.classList.add('is-hidden');
            iframe.setAttribute('src', '');
        }

        {% comment %} Code for making Tabs Work {% endcomment %}
        function openTab(evt, tabName) {
            var i, x, tablinks;
            x = document.getElementsByClassName("content-tab");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.querySelectorAll(".panel-tabs > a");
            for (i = 0; i < x.length; i++) {
                tablinks[i].classList.remove('is-active');
            }
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.classList.add("is-active");
        }

        {% comment %} Code for toggling document accepted {% endcomment %}
        const appr_btns = document.getElementsByClassName("appr-btn");

        function approveButtonHandler(e) {
            const btnType = this.getAttribute('data-btn-type')
            let confirmationStatus = false;
            switch(btnType) {
                case 'approve':
                    confirmationStatus = confirm('Are you sure you want to approve this document?');
                    break;
                case 'disapprove':
                    confirmationStatus = confirm('Are you sure you want to disapprove this document?');
                    break;
            }
            if (confirmationStatus) {
                const documentId = this.getAttribute('data-doc-id')
                window.location.href = `/group/{{ studentgroup.md5hash }}/toggle-document/${documentId}/`;
            }
        }

        for (let i = 0; i < appr_btns.length; i++) {
            appr_btns[i].addEventListener('click', approveButtonHandler)
        }

    </script>
{% endblock extra_js %}

templates/thesis/group_invite.html
{% extends 'base/thesis_dashboard_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} | Invite Group Members
{% endblock title %}


{% block page_title %}
    <h1 class="title">Invite Group Members</h1>
    <h2 class="subtitle">Share this code with your group members so that they can join this group!</h2>
{% endblock page_title %}


{% block dashboard_content %}
<div class="column">
    <p class="is-size-2 box has-background-link has-text-white" style="font-family:monospace;display:inline-block;">
        {{ studentgroup.md5hash }}</p>
    <br>
    <p class="help is-text-dark">
        P.S. The code is case-sensitive.
    </p>
    {% if studentgroup.approved %}
    <p class="help has-text-danger">
        Your group has been already approved by admin. <br>
        Contact admin if you have to add a new group member.
    </p>
    {% endif %}
</div>
{% endblock dashboard_content %}

templates/thesis/logbook_details.html
{% extends 'base/thesis_dashboard_base.html' %}
{% load static %}
{% load my_tags %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
{% endblock extra_css %}

{% block title %}
    {{ block.super }} | Logbook Details
{% endblock title %}


{% block page_title %}
    <h1 class="title">Logbook Details - {{ logbook.time }}</h1>
{% endblock page_title %}


{% block dashboard_content %}
<div class="column">
    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <tbody>
            <tr>
                <th style="width: 250px;">Time</th>
                <td>{{logbook.time}}</td>
            </tr>
            <tr>
                <th style="width: 250px;">Students Present</th>
                <td>{% for student in logbook.students_present.all %}{{ student }} <br>{% endfor %}</td>
            </tr>
            <tr>
                <th style="width: 250px;">Description of the work done after the last meeting with the supervisor:</th>
                <td>{{ logbook.work_done_after_last_meeting }}</td>
            </tr>
            <tr>
                <th style="width: 250px;">Description of the topic/issue discussed with or presented to the supervisor:</th>
                <td>{{ logbook.topic_discussed }}</td>
            </tr>
            <tr>
                <th style="width: 250px;">Suggestions and assignments obtained from the supervisor:</th>
                <td>{{ logbook.suggestions }}</td>
            </tr>
        </tbody>
    </table>

    {% if user == studentgroup.teacher %}
        {% if logbook.approved %}
            <a href="{% url 'thesis:toggle-logbook-approval' group_code=logbook.studentgroup.md5hash logbook_id=logbook.id %}" class="button is-danger">Disapprove</a>
        {% else %}
            <a href="{% url 'thesis:toggle-logbook-approval' group_code=logbook.studentgroup.md5hash logbook_id=logbook.id %}" class="button is-success">Approve</a>
        {% endif %}
    {% endif %}
</div>
{% endblock dashboard_content %}

templates/thesis/teacher_groups.html
{% extends 'base/base.html' %}

{% block title %}
    {{ block.super }} | Groups
{% endblock title %}


{% block content %}
    <h1 class="title">Teacher Groups</h1>
{% endblock content %}

templates/thesis/thesis_dashboard_base.html
{% extends 'base/base.html' %}


{% block extra_css %}
<style>
    nav.navbar {margin-bottom: 1rem;}
</style>
{% endblock extra_css %}


{% block content %}
{% url 'thesis:document_list' as document_list %}
{% url 'thesis:document_upload' as document_upload %}
{% url 'thesis:group_list' as group_list %}
{% url 'thesis:group_invite' as group_invite %}
{% url 'thesis:group_update' as group_update %}

<div class="container is-fluid">
    <div class="columns">
        <div class="column is-2">
            <div class="hero">
                <aside class="menu">
                    <p class="menu-label">Group</p>
                    <ul class="menu-list">
                        {% if user.is_teacher %}
                        <li><a href="{{ group_list }}"
                        class="{% if request.path == group_list %}is-active{% endif %}">
                            <i class="fas fa-align-justify"></i>&nbsp; Groups</a></li>
                        {% else %}
                        <li><a href="{{ document_list }}"
                        class="{% if request.path == document_list %}is-active{% endif %}">
                            <i class="fas fa-align-justify"></i>&nbsp; Documents</a></li>
                        <li><a href="{{ document_upload }}"
                        class="{% if request.path == document_upload %}is-active{% endif %}">
                            <i class="fas fa-upload"></i>&nbsp; Upload</a></li>
                        <li><a href="{{ group_invite }}"
                        class="{% if request.path == group_invite %}is-active{% endif %}">
                            <i class="fas fa-share"></i>&nbsp; Invite</a></li>
                        <li><a href="{{ group_update }}"
                        class="{% if request.path == group_update %}is-active{% endif %}">
                            <i class="fas fa-wrench"></i>&nbsp; Group Settings</a></li>
                        {% endif %}
                    </ul>
                    <p class="menu-label">Account</p>
                    <ul class="menu-list">
                        <li><a href="">
                            <i class="fas fa-cog"></i>&nbsp; Account Settings</a></li>
                        <li><a href="">
                            <i class="fas fa-trash"></i>&nbsp; Account Removal</a></li>
                    </ul>
                </aside>
            </div>
        </div>
        <div class="column">

            {% if studentgroup %}
            <h3 class="title">{{ studentgroup.title }}</h3>
            <h4 class="subtitle">Members:
                {{ studentgroup.students.all|join:", " }}.
            </h4>
            {% else %}
            <h3 class="title">Groups</h3>
            {% endif %}

            {% block dashboard_content %}
            {% endblock dashboard_content %}
        </div>
    </div>
</div>
{% endblock content %}